Repository ErwanLT/HackOktoberfest, pull requests merged in 2023-10, with the labels that each got.

#10 close create a data model #8
  README.md
Labels: hacktoberfest, hacktoberfest-accecpted

#11 init user API
  pom.xml
  src/main/java/fr/eletutour/hackOktoberfest/configuration/LoadDatabase.java
  src/main/java/fr/eletutour/hackOktoberfest/controller/UserController.java
  src/main/java/fr/eletutour/hackOktoberfest/domain/user/AppUser.java
  src/main/java/fr/eletutour/hackOktoberfest/exceptions/HackOktoberfestExceptionHandler.java
  src/main/java/fr/eletutour/hackOktoberfest/exceptions/UserException.java
  src/main/java/fr/eletutour/hackOktoberfest/repository/UserRepository.java
  src/main/java/fr/eletutour/hackOktoberfest/services/UserService.java
  src/main/resources/application.properties
  src/test/java/fr/eletutour/hackOktoberfest/HackOktoberfestApplicationTests.java
Labels: enhancement, hacktoberfest, hacktoberfest-accecpted

#12 init Brewery API
  src/main/java/fr/eletutour/hackOktoberfest/configuration/LoadDatabase.java
  src/main/java/fr/eletutour/hackOktoberfest/controller/BreweryController.java
  src/main/java/fr/eletutour/hackOktoberfest/domain/beer/Address.java
  src/main/java/fr/eletutour/hackOktoberfest/domain/beer/Brewery.java
  src/main/java/fr/eletutour/hackOktoberfest/exceptions/BreweryException.java
  src/main/java/fr/eletutour/hackOktoberfest/exceptions/HackOktoberfestExceptionHandler.java
  src/main/java/fr/eletutour/hackOktoberfest/repository/AdressRepository.java
  src/main/java/fr/eletutour/hackOktoberfest/repository/BreweryRepository.java
  src/main/java/fr/eletutour/hackOktoberfest/services/BreweryService.java
  src/main/resources/application.properties
Labels: enhancement, hacktoberfest, hacktoberfest-accecpted

#13 4 init openapi documentation
  pom.xml
  src/main/java/fr/eletutour/hackOktoberfest/configuration/OpenApiConfiguration.java
  src/main/java/fr/eletutour/hackOktoberfest/controller/BreweryController.java
  src/main/java/fr/eletutour/hackOktoberfest/controller/UserController.java
  src/main/java/fr/eletutour/hackOktoberfest/domain/beer/Brewery.java
  src/main/java/fr/eletutour/hackOktoberfest/exceptions/ErrorResponse.java
  src/main/java/fr/eletutour/hackOktoberfest/exceptions/HackOktoberfestExceptionHandler.java
  src/main/resources/application.properties
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accecpted

#14 Add postman collection with current api specs
  src/main/resources/Beer collection API.postman_collection.json
Labels: documentation, enhancement, hacktoberfest
